### ISSUE TITLE
Should the new C++ threaded kernel show up as a different resource?

### ISSUE THREAD

**Issue by rambaut** [beagle-dev/beagle-lib#101]
Currently resource 0 is the CPU (one core) and OpenCL across all cores shows up as a separate resource. It would be consistent if the new threaded kernel would also show up as a resource with appropriate flags set (i.e., THREADING).

**Comment by ayresdl** [comment]
In my mind resource 0 should the fastest resource that is highly portable and that fully implements the BEAGLE API. Unless we find some issues with the new threaded implementation, I would leave it as the default.

In contrast, the OpenCL CPU resource is not very portable (requires drivers), has gaps in implementation, and performance varies a lot, e.g. on macOS it can be slow.  The new threaded resource 0 is as portable as C++11 is and as far as I've seen is always faster than the previous non-threaded implementation. C++11 is an official release and supported by stable releases of gcc for a few years at least.

You can still disable threading with "BEAGLE_FLAG_THREADING_NONE" but that is in effect a testing feature as I can't think of a current scenario it would be faster or support more features.

**Comment by rambaut** [comment]
So resource 0 would automatically use up the entire machine? I guess this is a reasonable default. When the heterogenous hardware kernel is available that could then be resource 0 (i.e., use what ever hardware is available).

 It might be good to be able to limit the number of cores used (if, say, using a shared resource)? On possibility is to have some additional resources (a half machine and a quarter machine)?

**Comment by ayresdl** [comment]
That's a good point, forgot about that aspect. Currently we use half the number of threads reported by `std::thread::hardware_concurrency()`.

On Linux at least, one can limit the number of cores available to a process by launching it with the `taskset` utility.

**Comment by rambaut** [comment]
Perhaps as we move towards using heterogenous hardware, we need to think of some additional API for providing hardware limits (i.e., you will probably want to tell it to not use the low powered card used for the display).

**Comment by ayresdl** [comment]
Anyway, open to suggestions how to go forward for this release. I think my preferred options:
a) leave as is which means you have either all cores or just one via `THREADING_NONE`
b) new call in API to set number of cores
c) new resources with fewer cores (not to keen on this one)

**Comment by rambaut** [comment]
Fine for now. Closing the issue. Resource 0 should return the THREADING flag if it is using the C++11 threading kernel.
