### ISSUE TITLE
JAVAC compilation error

### ISSUE THREAD

**Issue by ghost** [beagle-dev/beagle-lib#111]
Hello team,
I have a persistent issue compiling beagle on my Ubuntu server. i will appreciate your helps . 

10.99.1.2 > ./configure --prefix=$HOME
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing lt_dlinit... -lltdl
checking for C compiler vendor... gnu
checking for C compiler version... 6.2.0
checking for /usr/include/CL... no
checking for /usr/local/cuda/... no
checking for /usr/local/cuda/include... no
checking for /usr/local/cuda/lib... no
checking for x86 cpuid 0x00000000 output... 4:756e6547:6c65746e:49656e69
checking for x86 cpuid 0x80000000 output... 8000000a:756e6547:6c65746e:49656e69
checking for x86 cpuid 0x00000001 output... 6d3:800:80002001:78bfbfd
checking for x86 cpuid 0x80000001 output... 6d3:0:1:2191abfd
checking whether RDRND is supported by the processor... no
checking whether BMI1 is supported by the processor... no
checking whether BMI2 is supported by the processor... no
checking whether ADX is supported by the processor... no
checking whether MPX is supported by the processor... no
checking whether PREFETCHWT1 is supported by the processor... no
checking whether ABM is supported by the processor... no
checking whether MMX is supported by the processor... yes
checking whether MMX is supported by the processor and OS... yes
checking whether C compiler accepts -mmmx... yes
checking whether SSE is supported by the processor... yes
checking whether SSE is supported by the processor and OS... yes
checking whether C compiler accepts -msse... yes
checking whether SSE2 is supported by the processor... yes
checking whether SSE2 is supported by the processor and OS... yes
checking whether C compiler accepts -msse2... yes
checking whether SSE3 is supported by the processor... no
checking whether SSSE3 is supported by the processor... no
checking whether SSE4.1 is supported by the processor... no
checking whether SSE4.2 is supported by the processor... no
checking whether SSE4a is supported by the processor... no
checking whether SHA is supported by the processor... no
checking whether AES is supported by the processor... no
checking whether AVX is supported by the processor... no
checking whether FMA3 is supported by the processor... no
checking whether FMA4 is supported by the processor... no
checking whether XOP is supported by the processor... no
checking whether AVX2 is supported by the processor... no
checking whether AVX512-F is supported by the processor... no
checking whether AVX512-CD is supported by the processor... no
checking whether AVX512-PF is supported by the processor... no
checking whether AVX512-ER is supported by the processor... no
checking whether AVX512-VL is supported by the processor... no
checking whether AVX512-BW is supported by the processor... no
checking whether AVX512-DQ is supported by the processor... no
checking whether AVX512-IFMA is supported by the processor... no
checking whether AVX512-VBMI is supported by the processor... no
checking cpuid.h usability... yes
checking cpuid.h presence... yes
checking for cpuid.h... yes
checking if javac works... configure: error: The Java compiler javac failed (see config.log, check the CLASSPATH?)

**Comment by koadman** [comment]
Does your system have a Java compiler? You should be able to run `javac` from the command-line. If not you may need to install java, which will require admin privleges. On recent ubuntu it can be done as: `sudo apt-get install openjdk-8-jdk`

**Comment by santiagosnchez** [comment]
I'm having the same error. I'm sure I have JDK installed. When I run:

    $ javac Test.java
    $ echo $?
    0

I get no errors. This only happens when running `./configure`.

    $ which javac
    /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/1.8.0_121/bin/javac

**Comment by santiagosnchez** [comment]
Ok. I made it work by giving the full path to the JDK installation:

    $ /configure --prefix=$HOME --with-jdk=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/1.8.0_121/

**Comment by baptelie** [comment]
Hi there, I am actually facing the same issue on ubuntu, and I have JDK installed. I tried to use the strategy adding `--with-jdk` but it didn't work:
`$ which javac
/usr/bin/javac
$ /configure --prefix=$HOME --with-jdk=/usr/bin/javac`
Should I try to point towards the original path and not the symlink ?

**Comment by ramin-zaghi** [comment]
@baptelie you seem to be using JDK 11. Is your problem because of this? @santiagosnchez is using version 8.

**Comment by EdYSChuang815** [comment]
I'm also having this same problem. I already set the JAVA_HOME and the CLASSPATH by
```
CLASSPATH=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el8_2.x86_64/lib/
export CLASSPATH
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el8_2.x86_64/
export JAVA_HOME
```
But it still failed when I run
`./configure --prefix=$HOME --with-jdk=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el8_2.x86_64/`
or
`./configure --prefix=$HOME`

With the error message:
`checking if javac works... configure: error: The Java compiler javac failed (see config.log, check the CLASSPATH?)`

Also the following is the path to my javac
```
$ readlink /usr/bin/javac
/etc/alternatives/javac
$ readlink /etc/alternatives/javac
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el8_2.x86_64/bin/javac
```
 I hope someone know how to fix this problem. Thanks.

**Comment by wellshl** [comment]
Hi @EdYSChuang815, 

Are you working on a server? I was able to solve this problem by making sure the job scheduler had enough virtual memory. In my case, 

`qlogin -l h_vmem=6G`

You can test this by just trying to run `javac` and if you get the error `Could not allocate metaspace: 1073741824 bytes` then this should be the solution to your problem.

Cheers,
Heather
