### ISSUE TITLE
"CUDA error: "Unknown error" from file <GPUInterfaceCUDA.cpp>, line 257."

### ISSUE THREAD

**Issue by fhsantanna** [beagle-dev/beagle-lib#112]
Hi.
I tried to run Beast using Beagle, however the following error occured:

"CUDA error: "Unknown error" from file <GPUInterfaceCUDA.cpp>, line 257."

My OS is Ubuntu 16.04. I installed CUDA 8.0 (and also 9.0), and everything seemed to be working well. At least the tests suggested by Nvidia manual were OK.

I followed the default instructions to install Beagle, and also tried to compile it using the option "--with-cuda=/usr/local/cuda-8.0", however I had no success. Also, Beagle passed in all tests after the installation (please see the attached file).
[test_beagle.txt](https://github.com/beagle-dev/beagle-lib/files/1674668/test_beagle.txt)

I look forward for your response.
Thank you.

**Comment by zjlahey** [comment]
I am running into this same error when trying to run mrbayes. I'm using cuda-9.1, beagle 2.1.2, and mrbayes 3.2.6.

**Comment by NilaBlueshirt** [comment]
I recently had a similar error when using beagle with beast1, and I re-installed beagle from the source codes, which resolved the error. My faulty beagle install was by spack on a linux cluster. Hope this info help!
