### ISSUE TITLE
opencl.h missing?

### ISSUE THREAD

**Issue by walterxie** [beagle-dev/beagle-lib#119]
@ayresdl @msuchard 
We were using the latest clone to build BEAGLE before testing BEAST 2, but it failed recently because of opencl.h was missing, and I fixed it by using the latest release v3.0.1.  https://github.com/CompEvol/beast2/issues/786

Error message:
/root/beagle-lib/libhmsbeagle/GPU/GPUInterface.h:57:31: fatal error: CL/opencl.h: No such file or directory
         #include <CL/opencl.h>

Please check if there is anything wrong in your current version.

**Comment by ayresdl** [comment]
Thanks for reporting this, it should be fixed now. I agree though that it's probably best to work with the last tagged version.
