### ISSUE TITLE
Failed to build beagle-lib 3.0.2 in Debian Stretch (9.4)

### ISSUE THREAD

**Issue by longbow0** [beagle-dev/beagle-lib#120]
I have searched in google and issues but cannot find the way to resolve this error.

The hardware information:

- Intel(R)  Xeon(R) CPU E5-2640 v4 @ 2.40GHz
- NVidia Tesla P100

The Linux system:
- Linux R730 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Both NVidia driver and CUDA are provided by Debian:
- nvidia-driver  375.82-1-deb9u1
- nvidia-cuda-dev  8.0.44-4
- nvidia-cuda-toolkit  8.0.44-4

- nvidia-opencl-dev:amd64  8.0.44-4
- nvidia-opencl-icd:amd64  375.82-1-deb9u1
- opencl-c-headers  2.1-1
- opencl-clhpp-headers  2.0.10-1

Build with `clang-3.8` and `export nvcc="nvcc -ccbin clang-3.8"` before make.

And error message:

> $ make
Making all in libhmsbeagle
make[1]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
make  all-recursive
make[2]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Making all in GPU
make[3]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
Making all in kernels
make[4]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
echo "// auto-generated header file with OpenCL kernels code" > BeagleOpenCL_kernels.h
echo "#define KERNELS_STRING_SP_4 \"" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
echo "#define STATE_COUNT 4" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./../GPUImplDefs.h | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./kernelsAll.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./kernels4.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
echo "\"" >> BeagleOpenCL_kernels.h
for s in 16 32 48 64 80 128 192; do \
        echo "Making state count = $s" ; \
        echo "#define KERNELS_STRING_SP_$s \"" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        echo "#define STATE_COUNT $s" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./../GPUImplDefs.h | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./kernelsAll.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./kernelsX.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        echo "\"" >> BeagleOpenCL_kernels.h; \
done
Making state count = 16
Making state count = 32
Making state count = 48
Making state count = 64
Making state count = 80
Making state count = 128
Making state count = 192
echo "#define KERNELS_STRING_DP_4 \"" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
echo "#define STATE_COUNT 4" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
echo "#define DOUBLE_PRECISION" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./../GPUImplDefs.h | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./kernelsAll.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
cat ./kernels4.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h
echo "\"" >> BeagleOpenCL_kernels.h
for s in 16 32 48 64 80 128 192; do \
        echo "Making state count = $s DP"; \
        echo "#define KERNELS_STRING_DP_$s \"" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        echo "#define STATE_COUNT $s" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        echo "#define DOUBLE_PRECISION" | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./../GPUImplDefs.h | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./kernelsAll.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        cat ./kernelsX.cu | sed 's/\\/\\\\/g' | sed 's/\"/\\"/g' | sed 's/$/\\n\\/' >> BeagleOpenCL_kernels.h; \
        echo "\"" >> BeagleOpenCL_kernels.h; \
done
Making state count = 16 DP
Making state count = 32 DP
Making state count = 48 DP
Making state count = 64 DP
Making state count = 80 DP
Making state count = 128 DP
Making state count = 192 DP
make  all-am
make[5]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
make[4]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
make[4]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../libhmsbeagle  -I/data/home/zeroliu/tmp/beagle-lib -I/data/home/zeroliu/tmp/beagle-lib -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -O3 -std=c++11 -pthread -march=native -DCUDA -I/usr/bin/include   -MT libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo -MD -MP -MF .deps/libhmsbeagle_cuda_la-GPUInterfaceCUDA.Tpo -c -o libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo `test -f 'GPUInterfaceCUDA.cpp' || echo './'`GPUInterfaceCUDA.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../libhmsbeagle -I/data/home/zeroliu/tmp/beagle-lib -I/data/home/zeroliu/tmp/beagle-lib -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -O3 -std=c++11 -pthread -march=native -DCUDA -I/usr/bin/include -MT libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo -MD -MP -MF .deps/libhmsbeagle_cuda_la-GPUInterfaceCUDA.Tpo -c GPUInterfaceCUDA.cpp  -fPIC -DPIC -o .libs/libhmsbeagle_cuda_la-GPUInterfaceCUDA.o
GPUInterfaceCUDA.cpp: In member function ‘void cuda_device::GPUInterface::InitializeKernelResource(int, bool)’:
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_4’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:240:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   -4: LOAD_KERNEL_INTO_RESOURCE(  4, DP,   4); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_16’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:241:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  -16: LOAD_KERNEL_INTO_RESOURCE( 16, DP,  16); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_32’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:242:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  -32: LOAD_KERNEL_INTO_RESOURCE( 32, DP,  32); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_48’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:243:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  -48: LOAD_KERNEL_INTO_RESOURCE( 48, DP,  48); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_64’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:244:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  -64: LOAD_KERNEL_INTO_RESOURCE( 64, DP,  64); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_80’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:245:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  -80: LOAD_KERNEL_INTO_RESOURCE( 80, DP,  80); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_128’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:246:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case -128: LOAD_KERNEL_INTO_RESOURCE(128, DP, 128); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_DP_192’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:247:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case -192: LOAD_KERNEL_INTO_RESOURCE(192, DP, 192); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_4’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:248:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case    4: LOAD_KERNEL_INTO_RESOURCE(  4, SP,   4); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_16’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:249:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   16: LOAD_KERNEL_INTO_RESOURCE( 16, SP,  16); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_32’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:250:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   32: LOAD_KERNEL_INTO_RESOURCE( 32, SP,  32); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_48’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:251:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   48: LOAD_KERNEL_INTO_RESOURCE( 48, SP,  48); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_64’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:252:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   64: LOAD_KERNEL_INTO_RESOURCE( 64, SP,  64); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_80’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:253:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case   80: LOAD_KERNEL_INTO_RESOURCE( 80, SP,  80); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_128’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:254:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  128: LOAD_KERNEL_INTO_RESOURCE(128, SP, 128); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
GPUInterfaceCUDA.cpp:49:21: error: ‘KERNELS_STRING_SP_192’ was not declared in this scope
             (char*) KERNELS_STRING_##prec##_##state, \
                     ^
GPUInterfaceCUDA.cpp:255:20: note: in expansion of macro ‘LOAD_KERNEL_INTO_RESOURCE’
         case  192: LOAD_KERNEL_INTO_RESOURCE(192, SP, 192); break;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:621: recipe for target 'libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo' failed
make[4]: *** [libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo] Error 1
make[4]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
Makefile:696: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
Makefile:616: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Makefile:459: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Makefile:607: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ayresdl** [comment]
Thank so for reporting. It looks like there was an issue with `nvcc` compiling the GPU kernels. Can you do a `make clean` before running `make` again? If you can then post the output from the first compilation run after a clean, I can see what is the `nvcc` error.

**Comment by longbow0** [comment]
Thank you! The output of `make` after `make clean` is:

> $ make
Making all in libhmsbeagle
make[1]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
make  all-recursive
make[2]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Making all in GPU
make[3]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
Making all in kernels
make[4]: Entering directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
echo "// auto-generated header file with CUDA kernels PTX code" > BeagleCUDA_kernels.h
/usr/bin/nvcc -o BeagleCUDA_kernels.ptx --default-stream per-thread -ptx -DCUDA -DSTATE_COUNT=4 \
	./kernels4.cu -O3 -arch compute_30 -Wno-deprecated-gpu-targets -DHAVE_CONFIG_H -I/data/home/zeroliu/tmp/beagle-lib -I/data/home/zeroliu/tmp/beagle-lib
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
       Use 'nvcc -ccbin clang-3.8' to use that instead.
Makefile:514: recipe for target 'BeagleCUDA_kernels.h' failed
make[4]: *** [BeagleCUDA_kernels.h] Error 1
make[4]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU/kernels'
Makefile:696: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle/GPU'
Makefile:616: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Makefile:459: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/data/home/zeroliu/tmp/beagle-lib/libhmsbeagle'
Makefile:607: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by longbow0** [comment]
It worked! Thank you very much!
