### ISSUE TITLE
Slow Performance issue with GPUs

### ISSUE THREAD

**Issue by chihwan** [beagle-dev/beagle-lib#123]
I have installed Beast 2.5.0 and Beagle-Lib 3.0.2(both latest version) on the Ubuntu 16.04. I thought there is no problem.
But I found some issues while doing some benchmark using GPUs. 
In the case of using GPUs with Beagle-Lib is almost 30% slower than CPUs. 
Would you give me some advice about this problem?

The hardware Information:
- Intel i3 6200 @ 3.7 Ghz
- Nvidia Tesla k20c
- Nvidia Quadro K6000 x 2
- Nvidia Quadro p4000 x 2
- DDR4 4Gb memory x 2

The Linux system:
- Ubuntu 16.04

The Software Information:
- nvidia-driver 396.xx
- nvidia-cuda 9.2 
- nvidia-cuda 8.0
- Beast 2.5.0
- Beast 1.10.0
- Beagle-lib (current version is 3.0.2)
- oracle jdk 9, 8, 7
- openjdk 9

My installation script is blow
./autogen.sh
./configure.sh --prefix=/usr/local --with-cuda=/usr/local/cuda-9.2
(./configure.sh --prefix=/usr/local --with-cuda=/usr/local/cuda-8.0)
sudo ./make 
sudo ./make install
sudo ./make check

All test is done successfully. 
My test result is blow:
6138.134 sec with GPU K6000 x 1
3913.724 sec with CPU 

**ah...I changed the version of beast 2.8.4 -> 2.5.0

**Comment by longbow0** [comment]
This happened to me. I works on a DELL server with 512G RAM and Tesla P100 card, the speed of Beast2 with beagle_GPU was about half of CPU only. The speed of CPU only and SSE was almost the same.

BTW, the current version of Beast2 is 2.5.0, and Beast 1.10.0.

**Comment by ayresdl** [comment]
Hello @chihwan, @longbow0. Thanks for reporting this performance issue. 

Depending on the specifications of the CPU, the GPU, and the data set, you may encounter cases where it is faster to run on the CPU. Generally, larger data sets and recent, high-end, NVIDIA GPUs are more likely to show speedups. We plan to address this issue in the near future by having BEAGLE automatically pick the best processor (i.e. CPU or GPU). In the meantime, I suggest running the analysis / data set in question for a few hundred generations and comparing run times, before starting a full inference run.

Daniel

**Comment by chihwan** [comment]
Hello @ayresdl @longbow0 
I really appreciate you guys answers. 
Without one exception, CPU is faster than the GPU in all tests. I think it is not normal situation...
Is there a best performance environment for the BEAST and BEAGLE-LIB?

**Comment by taprs** [comment]
For those who finds this thread later: I found that `beagle` + `beast2` performance heavily depends on the number of threads — there is always a sweet spot and deviations here or there reduce performance manifold. 

My usecase: three partitions, 300K nucleotides, 100 samples; 3 GPUS (beagle devices 1,2,3)

`beast -beagle_SSE -threads 64` gives 55 min per Msamples
`beast -beagle_SSE -threads 32` gives 50 min per Msamples
`beast -beagle_SSE -threads 16` gives 60 min per Msamples

`beast -beagle_GPU -threads 1` gives 120 min per Msamples
`beast -beagle_GPU -beagle_order 1,2,3 -threads 3` gives 70 min per Msamples
`beast -beagle_GPU -beagle_order 1,1,2,2,3,3 -threads 6` gives 9 min per Msamples (!!!)
`beast -beagle_GPU -beagle_order 1,1,1,1,2,2,2,2,3,3,3,3 -threads 12` gives 16 min per Msamples

So if in doubt, keep trying different numbers of threads!

**Comment by MJ720720** [comment]
> For those who finds this thread later: I found that `beagle` + `beast2` performance heavily depends on the number of threads — there is always a sweet spot and deviations here or there reduce performance manifold.
> 
> My usecase: three partitions, 300K nucleotides, 100 samples; 3 GPUS (beagle devices 1,2,3)
> 
> `beast -beagle_SSE -threads 64` gives 55 min per Msamples `beast -beagle_SSE -threads 32` gives 50 min per Msamples `beast -beagle_SSE -threads 16` gives 60 min per Msamples
> 
> `beast -beagle_GPU -threads 1` gives 120 min per Msamples `beast -beagle_GPU -beagle_order 1,2,3 -threads 3` gives 70 min per Msamples `beast -beagle_GPU -beagle_order 1,1,2,2,3,3 -threads 6` gives 9 min per Msamples (!!!) `beast -beagle_GPU -beagle_order 1,1,1,1,2,2,2,2,3,3,3,3 -threads 12` gives 16 min per Msamples
> 
> So if in doubt, keep trying different numbers of threads!

Thanks for the suggestion on this about trying different numbers of threads etc. 

I'm getting slow performance just like the OP, but no matter what I tried, still slow. Even weirder, is that the GPU is at 1% usage in task manager. Even though it is set as resource to use.
