### ISSUE TITLE
VCF header missing '>' at annotation lines

### ISSUE THREAD

**Issue by oushujun** [beagle-dev/beagle-lib#124]
Hello,

I was using beagle.27Jan18.7e1.jar and found the output VCF is missing '>' at the end of each INFO and FORMAT lines. This could cause errors in other programs which depends on reading the hearder information (e.g., [this](https://github.com/kern-lab/diploSHIC/issues/3))

Thanks for developing beagle!

Shujun

**Comment by koadman** [comment]
Hi Shujun, I think you've fallen victim to a bioinformatics software name collision. This github project is for the phylogenetic likelihood calculator library called beagle. You seem to be interested in this other beagle: https://faculty.washington.edu/browning/beagle/beagle.html
I suggest checking that website to see how to submit a support request.
