### ISSUE TITLE
Synthetictest Fail

### ISSUE THREAD

**Issue by Rengyx** [beagle-dev/beagle-lib#138]
Good day
I have install beagle for use with beast, doing the last step "make check" the following massage is display. Anyone have and idea what is causing the problem?
Big thanks in advance 

===============================================================
   libhmsbeagle 3.1.3: examples/synthetictest/test-suite.log
===============================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: synthetictest.sh
======================

ASSERTION FAILED: isa<GlobalValue>(CP) == false
  at file /build/beignet-Bevceu/beignet-1.3.2/backend/src/llvm/llvm_gen_backend.cpp, function void gbe::GenWriter::emitMovForPHI(llvm::BasicBlock*, llvm::BasicBlock*), line 2062

Simulating genomic DNA with 16 taxa and 10000 site patterns (5 reps, random seed 1)

Using resource 0:
	Rsrc Name : CPU
	Impl Name : CPU-4State-Single
	Flags: PRECISION_SINGLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW INVEVEC_STANDARD VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

logL = -103443.26127 
best run: 1.3530 ms

./synthetictest.sh: línea 1: 11257 «trap» para punto de parada/seguimiento                 (`core' generado) ./synthetictest
ASSERTION FAILED: isa<GlobalValue>(CP) == false
  at file /build/beignet-Bevceu/beignet-1.3.2/backend/src/llvm/llvm_gen_backend.cpp, function void gbe::GenWriter::emitMovForPHI(llvm::BasicBlock*, llvm::BasicBlock*), line 2062

Simulating genomic 64-state data with 10 taxa and 100 site patterns (5 reps, random seed 1)

Using resource 0:
	Rsrc Name : CPU
	Impl Name : CPU-Single
	Flags: PRECISION_SINGLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW INVEVEC_STANDARD VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

logL = -23571.40926 
best run: 20.7180 ms

./synthetictest.sh: línea 2: 11278 «trap» para punto de parada/seguimiento                 (`core' generado) ./synthetictest --states 64 --sites 100 --taxa 10
FAIL synthetictest.sh (exit status: 133)

**Comment by zcrabbit** [comment]
Same here!

===============================================================
   libhmsbeagle 3.2.0: examples/synthetictest/test-suite.log
===============================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: synthetictest.sh
======================

dyld: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/chengzhang/Downloads/beagle-lib-master/examples/synthetictest/.libs/synthetictest (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/chengzhang/Downloads/beagle-lib-master/examples/synthetictest/.libs/synthetictest
./synthetictest.sh: line 1: 27630 Abort trap: 6           ./synthetictest
dyld: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/chengzhang/Downloads/beagle-lib-master/examples/synthetictest/.libs/synthetictest (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/chengzhang/Downloads/beagle-lib-master/examples/synthetictest/.libs/synthetictest
./synthetictest.sh: line 2: 27645 Abort trap: 6           ./synthetictest --states 64 --sites 100 --taxa 10
FAIL synthetictest.sh (exit status: 134)

**Comment by jinz2014** [comment]
> Good day
> I have install beagle for use with beast, doing the last step "make check" the following massage is display. Anyone have and idea what is causing the problem?
> Big thanks in advance
> 
> # ===============================================================
> libhmsbeagle 3.1.3: examples/synthetictest/test-suite.log
> # TOTAL: 1
> # PASS: 0
> # SKIP: 0
> # XFAIL: 0
> # FAIL: 1
> # XPASS: 0
> # ERROR: 0
> .. contents:: :depth: 2
> 
> # FAIL: synthetictest.sh
> ASSERTION FAILED: isa(CP) == false
> at file /build/beignet-Bevceu/beignet-1.3.2/backend/src/llvm/llvm_gen_backend.cpp, function void gbe::GenWriter::emitMovForPHI(llvm::BasicBlock*, llvm::BasicBlock*), line 2062
> 
> Simulating genomic DNA with 16 taxa and 10000 site patterns (5 reps, random seed 1)
> 
> Using resource 0:
> Rsrc Name : CPU
> Impl Name : CPU-4State-Single
> Flags: PRECISION_SINGLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW INVEVEC_STANDARD VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
> 
> logL = -103443.26127
> best run: 1.3530 ms
> 
> ./synthetictest.sh: línea 1: 11257 «trap» para punto de parada/seguimiento (`core' generado) ./synthetictest
> ASSERTION FAILED: isa(CP) == false
> at file /build/beignet-Bevceu/beignet-1.3.2/backend/src/llvm/llvm_gen_backend.cpp, function void gbe::GenWriter::emitMovForPHI(llvm::BasicBlock*, llvm::BasicBlock*), line 2062
> 
> Simulating genomic 64-state data with 10 taxa and 100 site patterns (5 reps, random seed 1)
> 
> Using resource 0:
> Rsrc Name : CPU
> Impl Name : CPU-Single
> Flags: PRECISION_SINGLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW INVEVEC_STANDARD VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
> 
> logL = -23571.40926
> best run: 20.7180 ms
> 
> ./synthetictest.sh: línea 2: 11278 «trap» para punto de parada/seguimiento (`core' generado) ./synthetictest --states 64 --sites 100 --taxa 10
> FAIL synthetictest.sh (exit status: 133)

Does it work for other OpenCL kernels which are not related to Beagle  on an Intel GPU ?

**Comment by jinz2014** [comment]
> /usr/lib/libstdc++.6.dylib

 I am not familiar with mac os, but you may need to install the missing library /usr/lib/libstdc++.6.dylib. I don't think the issue is caused by Beagle.

**Comment by roussine** [comment]
_Same problem, different cause. Perhaps unrelated to actual threats, but please comment if someone's an idea:_

===============================================================
   libhmsbeagle 3.2.0: examples/synthetictest/test-suite.log
===============================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: synthetictest.sh
======================

DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
./synthetictest.sh: line 1:  9361 Segmentation fault      ./synthetictest
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
./synthetictest.sh: line 2:  9389 Segmentation fault      ./synthetictest --states 64 --sites 100 --taxa 10

**Comment by EvolDoc** [comment]
Same problem using . Wondering if anyone has found a solution.
