### ISSUE TITLE
Instal fail on supercomputer

### ISSUE THREAD

**Issue by LTBroda** [beagle-dev/beagle-lib#140]
Hi guys,

I'm experiencing install error of Beagle lib. v 3.1.2 on computing node with slurm 17.02.9 and Scientific Linux release 6.10 (Carbon).
With basic parameters installation goes smoothly, but it wan't run with MrBayes 3.2.7a on more than one node. I assume that I require '--enable-openmp' flag so it works with openmpi. Unfortunately with that flag make fails with Error code 2 ([install-am]) and 1 ([install-libLTLIBRARIES] and [install-recursive]). make check indicates fail with tinytest.

Do you have any experience with installation of Beagle on supercomputers or have any idea how to solve this problem?

Best regards,
Łukasz

**Comment by koadman** [comment]
Hi Łukasz, OpenMP and OpenMPI are two different things. OpenMP supports multiple threads on a single system image (e.g. a single node in your 'supercomputer'), OpenMPI supports communication among different system images/nodes. In your case it is probably enough to just use OpenMPI, so you can build without the `--enable-openmp` flag. If you want to get OpenMP working we'll probably need more details from the build log. The error numbers don't tell us much.

**Comment by LTBroda** [comment]
Thank you koadman for your response.
What you suggest I did at the beginning, but got error  so in my desperation I tried different things...

MrBayes Error:

> Running benchmarks to automatically select fastest BEAGLE resource... Unable to load CPU plugin!
> Please check for proper libhmsbeagle installation.
>       Failed to start BEAGLE instance
> 
>       Running benchmarks to automatically select fastest BEAGLE resource...       Failed to start BEAGLE instance
>       Using standard FMA likelihood calculator

**Comment by LTBroda** [comment]
OK, I solved this. MrBayes needs some local variables to locate beagle.
`export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH` solved my problem.
Sorry for wasting your time and gave a great day!
