### ISSUE TITLE
no hmsbeagle-jni in java.library.path

### ISSUE THREAD

**Issue by Adelaam** [beagle-dev/beagle-lib#141]
Hello,

I am trying to run Beast but I got this error on ubuntu: Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: I have downloaded the lib too.

Thank you!

**Comment by J-Moravec** [comment]
Did you put path to Beagle libs to your LD_LIBRARY_PATH and restarted your environment (or just sourced said file, I usually put it either into .bashrc or .profile)?

See this step in manual:
https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions#step-3-set-environment-variables

**Comment by msuchard** [comment]
Closing.   Please re-open if issue still exists.

**Comment by dc27708** [comment]
Dear Admin,

I've successfully installed Beagle locally in my home in the IFB cluster following: https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions

(base) [dchakraborty@core-login2 ~]$ cd $HOME
(base) [dchakraborty@core-login2 ~]$ ls
00_data 01_mafft R include lib ondemand user_guides
(base) [dchakraborty@core-login2 ~]$ cd lib
(base) [dchakraborty@core-login2 lib]$ ls
cmake libhmsbeagle-cpu-sse.so.40.0.0 libhmsbeagle-cpu.so.40.0.0 libhmsbeagle.so pkg-config
libhmsbeagle-cpu-sse.so libhmsbeagle-cpu.so libhmsbeagle-jni.so libhmsbeagle.so.1

But when I try <beast -beagle_info>, beast can't access beagle. <Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /.singularity.d/libs:/usr/local/lib:/usr/local/beast/jre/lib/amd64>

I've added the path to the library to .bashrc.

Thank you in advance for any pointers.
Debo
