### ISSUE TITLE
Compiling fails to find OpenCL

### ISSUE THREAD

**Issue by TorstenEriksson** [beagle-dev/beagle-lib#142]
Recently had to upgrade to Ubuntu 18.04 (NVIDIA Quadro K2200 GPU)  and while updating and reinstalling stuff, compiling  Beagle-lib fails. I have installed cuda-10.1 and used similar configuration that worked previously:

./configure --prefix=/usr/local --with-opencl=/usr/local/cuda/lib64

Then
...
make[3]: Entering directory '/usr/local/src/beagle/beagle-lib/libhmsbeagle/GPU'
...keeps going for a while and fails with:

/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -O3 -std=c++11 -march=native -D FW_OPENCL -I/usr/local/cuda/lib64/include  -module -version-number 32  -o libhmsbeagle-opencl.la -rpath /usr/local/lib libhmsbeagle_opencl_la-GPUImplHelper.lo libhmsbeagle_opencl_la-GPUInterfaceOpenCL.lo libhmsbeagle_opencl_la-KernelLauncher.lo libhmsbeagle_opencl_la-KernelResource.lo libhmsbeagle_opencl_la-OpenCLPlugin.lo -lOpenCL -ldl 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o  .libs/libhmsbeagle_opencl_la-GPUImplHelper.o .libs/libhmsbeagle_opencl_la-GPUInterfaceOpenCL.o .libs/libhmsbeagle_opencl_la-KernelLauncher.o .libs/libhmsbeagle_opencl_la-KernelResource.o .libs/libhmsbeagle_opencl_la-OpenCLPlugin.o   -lOpenCL -ldl -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o  -O3 -march=native   -Wl,-soname -Wl,libhmsbeagle-opencl.so.32 -o .libs/libhmsbeagle-opencl.so.32.0.0
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
Makefile:577: recipe for target 'libhmsbeagle-opencl.la' failed
make[3]: *** [libhmsbeagle-opencl.la] Error 1
make[3]: Leaving directory '/usr/local/src/beagle/beagle-lib/libhmsbeagle/GPU'
Makefile:700: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/usr/local/src/beagle/beagle-lib/libhmsbeagle/GPU'
Makefile:622: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/beagle/beagle-lib/libhmsbeagle'
Makefile:611: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by nylander** [comment]
Hej @TorstenEriksson !

Beagle's configure script should be able to pick up the necessary files automatically. If not, try to provide the path to the folder containing the file (or symlink)  `libOpenCL.so` as the argument to `--with-opencl=`. Maybe it isn't located in `/usr/local/cuda/lib64`?

As a note, there are alternative sources for OpenCL (NVIDIA is one provider), and they differ in how successful they are providing the desired functionality on Ubuntu. If your current version doesn't work, you may consider using alternative sources (see, e.g., the output from `apt-file search libOpenCL.so`).

Furthermore, depending on how you are planning to use the beagle library, you may need to apply additional steps in the compile process (see e.g., https://github.com/beagle-dev/beagle-lib/issues/134#issuecomment-460661203).

/Johan

**Comment by msuchard** [comment]
Assuming this is taken care of and closing.  If issue remains, please re-open.

**Comment by TorstenEriksson** [comment]
Sorry. I do not seem to be allowed to re-open the issue.  Anyway, the suggestions by @nylander had no noticeable effect. The mentioned library file is there. I noticed that the configure script looked for /usr/local/cuda/lib so I added symbolic link (had lib64), but to no avail. 

Whatever I have done it fails with: /usr/bin/ld: cannot find -lOpenCL

**Comment by bolbatav** [comment]
After lots of trial and error I have found that beagle simply does not play nice with OpenCL, no matter what you do. In my case it led to "**OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 115**" 100% of the time.
Use CUDA and Nvidia proprietary drivers.
`./configure --without-opencl --with-cuda="/path/to/cuda/directory/"`

**Comment by msuchard** [comment]
This is simply not true.  10s to 100s of users (including ourselves) use OpenCL through BEAGLE every day.   Further, the upcoming build process uses `cmake` in, e.g., the `v4_release` branch.  You may have better luck defining the appropriate paths for your own system (not a BEAGLE issue).

**Comment by TorstenEriksson** [comment]
Sorry to see this close again. I returned from Covid-19 forced office absence and started to get this to work again. I have installed a new version of cuda. As far as I can see (chain of symbolic links) the library is there. Still the linker can not find the openCL library. The solution suggested above by @bolbatav kind of works, but causes other problems when using the library (in mrbayes).

**Comment by cement-head** [comment]
For me, on Pop!_OS 22.04 with CUDA installed, I had to use this command:

`$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DOpenCL_FOUND=True -DOpenCL_LIBRARY="/usr/lib/cuda/lib64/libOpenCL.so.1.0.0" -DOpenCL_INCLUDE_DIR="/usr/lib/cuda/targets/x86_64-linux/include/CL/" ..`

That enabled BEAGLE3 to build _both_ the OpenCL and the CUDA libraries.
