### ISSUE TITLE
BEAST cannot find Beagle library

### ISSUE THREAD

**Issue by aine-c** [beagle-dev/beagle-lib#146]
I am a complete computer novice so there may be an obvious fix to this.
I have downloaded and run the BEAGLE.v3.1.0 installer for Windows, and then restarted the computer. 
When I then open Beast, and I click 'show list of available BEAGLE resources and Quit' and run it, Beast gives me 'Failed to load BEAGLE library: no hmsbeagle32 in java.library.path'
This is listed as a linux error here https://beast.community/errors.html (for hmsbeagle-jni in java.library.path) but not sure why I'm getting a similar message on my Windows system?

Any help gratefully received!

**Comment by samanthasvid** [comment]
hi!!! i have the same problem as you, open i found any solution? It would be very helpful to me right now

**Comment by xji3** [comment]
@aine-c @samanthasvid Just for the record, I recently fixed the same issue for a friend, it turned out my friend was using 32-bit java environment.  The fix was really simple: install java JDK from the link provided on the BEAST installing page(http://beast.community/install_on_windows): http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by samanthasvid** [comment]
@xji3 Thank you very much, one more question after the java installation did you reinstall BEAS and Beagle? or just reboot?

**Comment by samanthasvid** [comment]
@xji3 Thank you very much, that was the problem. Greetings

**Comment by xji3** [comment]
@samanthasvid You are welcome.

**Comment by nilani-chandradeva1** [comment]
I've installed the 64-bit version but getting the same error message. Does the file path of java JDK matter?

**Comment by xji3** [comment]
@nilani-chandradeva1 I think that if your 64-bit is correctly installed, then the problem is the system environment setup where you want to check if the java being used is indeed the 64-bit version.
