### ISSUE TITLE
BEAGLE doesn't recognize GPU

### ISSUE THREAD

**Issue by margot-l** [beagle-dev/beagle-lib#148]
Hi,
I'm trying to use BEAGLE library v3.1.0 with BEAST v1.10.4. 

I have a mid-2015 MacBookPro with two graphics card, an AMD Radeon R9 M370X (PCIe) and an Intel Iris Pro (built-in).

When I run "beast -beagle_info" it outputs 

> BEAGLE resources available:
> 0 : CPU
>     Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_SSE VECTOR_NONE THREADING_CPP THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

No mention of GPU at all. Neither are NVIDIA so CUDA won't help. Any ideas?

Thanks.

**Comment by Ciznetwork** [comment]
I also have this issue with my MacBook pro-2017. Any Ideas pls?

**Comment by bryankolaczkowski** [comment]
I can chime in in general, although I've only ever built CUDA applications for GPU. 
In general, there is insufficient information in your bug report to effectively diagnose the issue. 

Can you confirm that other OpenCL applications work on your hardware? 
Can you confirm that beagle was built with OpenCL support? Is it a binary install, or compiled? If binary, can you try to compile beagle from source on your hardware, to see if configuration recognizes the OpenCL libraries and tries to build an OpenCL application?

What OS version?
What GPU driver version?   

In general, the more documentation you can provide, the better. Any messages during package installs could be useful; compile messages are typically more useful, if they are available. 

I don't know what kind of debugging or verbose runtime options beagle has, but compiling with debugging symbols and turning on as many runtime info flags as possible generally makes it much easier to figure out where hardware recognition might be failing. If the library has insufficient runtime messages, you can always insert them into source code, but that might take some digging. 

Again, I have very limited knowledge of OpenCL, so I can't really help there, but if you want to get some movement on this issue, I'd suggest doing whatever you can on your end to diagnose where the recognition failure might be occurring. For better or worse, bug reports with more thorough and detailed information tend to get resolved quicker.

I hope that helps you resolve your issue.

**Comment by seppegoovaerts** [comment]
I also have this issue. Have any of you already found out how to resolve this?

**Comment by xji3** [comment]
@MuriloACassiano Sorry for bringing you trouble.  Could you detail out the difficulties that you face in a separate issue?  I am closing this issue for now as we changed to cmake builds.
