### ISSUE TITLE
beagle install issue

### ISSUE THREAD

**Issue by oscarIM** [beagle-dev/beagle-lib#154]
I tried to install the library with cuda driver 11 (on an Ubuntu 20.10 machine). However, when compiling I throw the following error:
**nvcc fatal: Value 'sm_30' is not defined for option 'gpu**. For this, I replace in the Makefile (libhmsbeagle/GPU **/Kernels/Makefile) NVCCFLAGS = -O3 -arch compute_30 -Wno-deprecated-gpu-targets** by **NVCCFLAGS = -O3 -arch compute_75 -Wno-deprecated-gpu-targets**. With this it installs without errors, but when trying to use the library together with the BEAST 2 program, it does not work, throwing the following error: CUDA error: "Unknown error" from file <GPUInterfaceCUDA.cpp>, line 294.

Some clue? Or will I just have to install older versions of cuda

Cheers

**Comment by NilaBlueshirt** [comment]
I recently had a similar error when using beagle with beast1, and I re-installed beagle from the source codes, which resolved the error. My faulty beagle install was by spack on a linux cluster. Hope this info helps!
