### ISSUE TITLE
Assistance on deploying beast + beagle lib

### ISSUE THREAD

**Issue by Aymenchaalia** [beagle-dev/beagle-lib#164]
Can the developper assist me on addidng Matrox video card to the beagle lib script ? as it actually contains only : Apple, Intel, Nvidea and AMD.
I need to run beast with beagle lib on a machine that contains Matrox video card

**Comment by msuchard** [comment]
As far as I can tell, Matrox video cards do not provide general purpose graphics processing unit (GP-GPU) functionality.  They are traditional video cards to drive multiple displays.  I could, however, be wrong and if you could provide me with some code examples of Matrox cards executing OpenCL or CUDA, I can help modify BEAGLE.

Am closing this issue for now.
