### ISSUE TITLE
beagle-lib master CUDA fails build at 54% at ~/beagle-lib/libhmsbeagle/GPU/GPUInterfaceCUDA.cpp:41 -> Missing file libhmsbeagle/GPU/kernels/BeagleCUDA_kernels.h

### ISSUE THREAD

**Issue by caaguado** [beagle-dev/beagle-lib#168]
Hi there,

My system:
- Ubuntu Desktop 21.10 (amd64)
- Linux kernel 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Nvidia drivers nvidia-driver-495, 495.29.05-0ubuntu1 amd64 (latest available as of opening this issue report).
- CUDA Toolkit nvidia-cuda-toolkit 11.3.1-4 amd64

Trying to build beagle-lib master for CUDA, following the official Beagle Linux installation instructions at:
https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions

With commands:

$ git clone --depth=1 https://github.com/beagle-dev/beagle-lib.git
$ cd beagle-lib
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME -DBUILD_OPENCL=OFF ..
$ make install

I get a compilation error at 54% of the build process at:

~/beagle-lib/libhmsbeagle/GPU/GPUInterfaceCUDA.cpp:41

Due to an apparently missing file libhmsbeagle/GPU/kernels/BeagleCUDA_kernels.h

Like this:

Scanning dependencies of target hmsbeagle-cuda
[ 50%] Building CXX object libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/__/GPUImplHelper.cpp.o
[ 54%] Building CXX object libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/__/GPUInterfaceCUDA.cpp.o
In file included from /home/pablichu/beagle-lib/libhmsbeagle/GPU/GPUInterfaceCUDA.cpp:41:
/home/pablichu/beagle-lib/libhmsbeagle/GPU/GPUInterface.h:46:18: fatal error: libhmsbeagle/GPU/kernels/BeagleCUDA_kernels.h: No such file or directory
   46 |         #include "libhmsbeagle/GPU/kernels/BeagleCUDA_kernels.h"
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/build.make:95: libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/__/GPUInterfaceCUDA.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:300: libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Looking at the master branch, the mentioned file indeed seems to be missing.

Could you please kindly add the mentioned file "libhmsbeagle/GPU/kernels/BeagleCUDA_kernels.h", as well as any other eventually missing files, to the master branch, so I could re-fetch it and build it?

I guess this same issue may affect other people as well.

Thanks a lot and, by the way, congratulations for the fantastic work on the library; highly appreciated!

PS: I'm attaching a full logfile of the issue, in case it may be helpful :-)
[beagle-lib_with_cuda_build_failure_missing_include_files_caaguado_20211031.log](https://github.com/beagle-dev/beagle-lib/files/7449419/beagle-lib_with_cuda_build_failure_missing_include_files_caaguado_20211031.log)

**Comment by msuchard** [comment]
Your error is here:

```
[ 45%] Building CUDA kernels
NVCC=/usr/local/cuda/bin/nvcc
NVCCFLAGS=-O3 -Wno-deprecated-gpu-targets -ccbin /usr/bin/c++ -m64 -D_POSIX_C_SOURCE -std=c++11
INCLUDE_DIRS=-I/home/pablichu/beagle-lib
/usr/include/stdio.h(183): error: attribute "__malloc__" does not take arguments
```

which suggests incapability between `nvcc` and your C++ compiler `GNU11.2`.  This requires further exploration.

`BeagleCUDA_kernels.h` is *not* missing; this file gets formed from the output from `nvcc`.

**Comment by caaguado** [comment]
Thanks Marc for the super-fast response. Is there anything I can do to help investigate the incapability issue?
   
  
  
   
  
  
   Could this be any sort of misconfiguration on the Nvidia drivers or CUDA Toolkit side?
  
  
   
  
  
   Best regards.
  
  
   
    On 2021-10-31 19:35 Marc Suchard ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Your error is here:
   [ 45%] Building CUDA kernels
NVCC=/usr/local/cuda/bin/nvcc
NVCCFLAGS=-O3 -Wno-deprecated-gpu-targets -ccbin /usr/bin/c++ -m64 -D_POSIX_C_SOURCE -std=c++11
INCLUDE_DIRS=-I/home/pablichu/beagle-lib
/usr/include/stdio.h(183): error: attribute "__malloc__" does not take arguments

   which suggests incapability between nvcc and your C++ compiler GNU11.2. This requires further exploration.
   BeagleCUDA_kernels.h is not missing; this file gets formed from the output from nvcc.

**Comment by biofilos** [comment]
I am in Fedora, and according to their [Howto CUDA](https://rpmfusion.org/Howto/CUDA), I have to install an older version of `c++` called `cuda-c++`.  
How can I change the compiler used, so that it uses `cuda-c++`
Thanks!

**Comment by msuchard** [comment]
Please see the documentation pages for `cmake` to learn how to personalize your configuration: https://cmake.org/cmake/help/latest/manual/cmake.1.html

 There are command-line options like `-DCMAKE_CXX_COMPILER=<yourpath>/g++ -DCMAKE_CC_COMPILER=<yourpath>/gcc`.   These variables get passed to `nvcc` inside `libhmsbeagle/GPU/CMake_CUDA/CMakeLists.txt`.

**Comment by biofilos** [comment]
Thanks for the answer. I was able to build Beagle-lib using the command `cmake -DBUILD_OPENCL=OFF -DCMAKE_CXX_COMPILER=/usr/bin/cuda-g++ -DCMAKE_CC_COMPILER=/usr/bin/cuda-gcc`

Maybe if OP can downgrade g++ and cpp, it might work. In my case, I think `cuda-g++` is just a downgraded `g++` . For reference, it is version 8.3.0 in my case

**Comment by Alqueno** [comment]
on Ubuntu 20.04 the issue still exists. installing g++-7 and gcc-7 from canonical repositories and pointing to them as biofilos says will compile.
