### ISSUE TITLE
Apple Silicon M1 series support

### ISSUE THREAD

**Issue by sam-mic** [beagle-dev/beagle-lib#170]
Professor Andrew Rambaut has mentioned successful implementation of beagle-lib on M1 chip. Any tutorials on how to achieve this? And the performance on M1 Max / Pro chips. It's really excited to see the results.

**Comment by xji3** [comment]
There should be no difference using the `cmake` build.  I don't think we have any benchmarking with the newer M1 Max/Pro chips yet.

**Comment by sam-mic** [comment]
> There should be no difference using the `cmake` build. I don't think we have any benchmarking with the newer M1 Max/Pro chips yet.

Hi, I've tried to use cmake according to the tutorial, but it returns "Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)". I'm sure JAVA has been installed, but the PATH is not written into the ~/.bash_profile properly. 

So I use Conda to install the beagle-lib and BEAST, but failed to use beagle-lib and GPU to accelerate the BEAST (-beagle_GPU and -beagle_opencl).  

My computer is M1 chip. 

Thank you for your answering!

**Comment by xji3** [comment]
Thank you for bringing this up.  I added a short FAQ section for this issue.  Could you try it and let me know?

**Comment by sam-mic** [comment]
(1) I downloaded and installed the JAVA JDK version 17.0.1+12 (Zulu: 17.30.15) of macOS 11.0 or later (ARM 64-bit v8). This is installed in /Library/Java/JavaVirtualMachines/zulu-17.jdk/
so I export the "JAVA_HOME"path to a subfolder (which contains two head "jawt_md.h" & "jni_md.h") using: 
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/include/darwin/`

(2) The "jhi.h" is in `/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/include/`

so I export other PATHs using: `export JAVA_INCLUDE_PATH=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/include/`

`export JAVA_INCLUDE_PATH2=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/include/`

`export JAVA_AWT_INCLUDE_PATH=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/include/`


(3) I also tried :` export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/`

Still not work.

(My system is Mac OS Monterey (V 12.0.1) with Apple M1 Max chip.)

**Comment by msuchard** [comment]
The ability of `cmake` to correctly find Java has not yet been tested on macOS Monterey.   Note this is not a `BEAGLE` issues, but rather a `cmake` issue.  

In the meantime, you can compile `BEAGLE` without JNI support and copy over `libhmsbeagle-jni.jnilib` into your install directory from an older version.  (This library component has not changed.)

**Comment by xji3** [comment]
@sam-mic That's weird.  I am not exactly sure how much different Monterey is from Big Sur.  But I will try with my Big Sur system anyway.  Could you share the error message with me after these steps:
1. `cd beagle-lib` (where you store beagle-lib repository)
2. `rm -rf build`
3. `mkdir build`
4. `cd build`
5. `export JAVA_HOME=export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`
6. `cmake ..` (You should be able to see `Found JNI: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/lib/libjawt.dylib` and `JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`)
7. `make install`

Thanks!

**Comment by sam-mic** [comment]
Thank you all for the instructions! Yes this works, I successfully build and install the beagle-lib using `cmake -DBUILD_CUDA=OFF ..`
(1) When I use beast2 (GUI version with JAVA) to list the available BEAGLE resources, it returns

--- BEAGLE RESOURCES ---

0 : CPU (x86_64)
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_SSE VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

1 : Apple M1 Max (OpenCL 1.2 )
    Global memory (MB): 21845
    Clock speed (Ghz): 1.00
    Number of compute units: 24
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH COMPUTATION_ASYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_NONE THREADING_NONE PROCESSOR_GPU FRAMEWORK_OPENCL

However, When I run the beast2 with prefer use of GPU and use BEAGLE library if available, it returns the following but not use GPU

Using BEAGLE version: 4.0.0 (PRE-RELEASE) resource 0: CPU (x86_64)
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU
===============================================================================

(2) What I installed was [BEAGLE v2.1.2 for Mac OS X 10.6 and later] because the link to download [BEAGLE v4.0.0 for macOS universal] is not available currently.
So I guess the GUI verion of beast2 (with JAVA) can't recognize the beagle-lib I installed and use its own. 
Next, I tried commandline version (without JAVA) to print beagle info (~/Downloads/BEAST\ 2.6.6/bin/beast -beagle_info), it returns

--- BEAGLE RESOURCES ---

Failed to load BEAGLE library: /Library/Java/Extensions/libhmsbeagle-jni.jnilib: dlopen(/Library/Java/Extensions/libhmsbeagle-jni.jnilib, 0x0001): tried: '/Library/Java/Extensions/libhmsbeagle-jni.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libhmsbeagle-jni.jnilib' (no such file)

===============================================================================

Thanks again

**Comment by xji3** [comment]
@sam-mic You want to use the version of BEAST2 without java.  With BEAGLE built using `cmake`, you don't need to install BEAGLE again (and you don't want to use BEAGLE v2 either).  By default, the BEAGLE library is installed into `/usr/local/lib`, you can confirm this by testing if `ls -lt /usr/local/lib/*beagle*` returns a list of built BEAGLE libraries.

Your guess of the GUI version of BEAST2 is very likely correct.  Your command missed an environment variable (`BEAGLE_LIB` used in the bash script of `BEAST\ 2.6.6/bin/beast`).  I was able to see my BEAGLE info correctly with the environment variable set.  Please try the following slightly modified command with your path `BEAGLE_LIB=/usr/local/lib ~/Downloads/BEAST\ 2.6.6/bin/beast -beagle_info` which assumes the BEAGLE library is installed at the default location.

Lastly, we currently do not recommend using GPU on M1 macs.  But if you just want to give it a try, you might want to add flags `-beagle_GPU -beagle_single`.  I attach the output of my beagle resource list, please note the `(arm64)` for the CPU build.  You want to confirm this so that the BEAGLE build is ARM64 native (rather than x86_64 through Rosetta).

--- BEAGLE RESOURCES ---

0 : CPU (arm64)
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_SSE VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

1 : Apple M1 (OpenCL 1.2 )
    Global memory (MB): 10922
    Clock speed (Ghz): 1.00
    Number of compute units: 8
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH COMPUTATION_ASYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_NONE THREADING_NONE PROCESSOR_GPU FRAMEWORK_OPENCL

**Comment by sam-mic** [comment]
Thanks again, works now. Cheers~

By the way. It is faster to use `-beagle_sse` than `-beagle_gpu` in my computer (%GPU = 90 in activity monitor).

If I run `BEAGLE_LIB=/usr/local/lib  ~/Downloads/BEAST1.10.5/bin/beast -beagle_sse input.xml`, the speed is 2.06 minutes/million states (if I understand correctly)
If I run `BEAGLE_LIB=/usr/local/lib  ~/Downloads/BEAST1.10.5/bin/beast -beagle_gpu -beagle_single input.xml`, the speed is  1.57 hours/million states. (much slower)
