### ISSUE TITLE
Mr Bayes chains stuck 

### ISSUE THREAD

**Issue by joqb** [beagle-dev/beagle-lib#173]
Hi,
I am trying to run a Mcmc-analysis with MrBayes (3.2.7a) in combination with the beagle library (4.0) on a Linux server either regular CPU, and using slurm-cpu, or slurm-gpu.
The dataset consisting of whole chloroplasts is medium-large: 278 individuals and 150.000 bp long (35.000 unique site patterns).
I observed weird behavior from the mcmc (see attached likelihood traces from Tracer) and this issue seems to be related to the beagle library and also to memory usage as running MrBayes without beagle ran properly, while running with it either got the chains jumping and getting stuck and being kicked out of the system because it used too much memory. 

Nay idea what is going wrong?

Best regards
Jonathan

![image](https://user-images.githubusercontent.com/11645116/151118568-78b2dc98-d56a-4380-9ae4-fb2c3ecdfa99.png)
<img width="894" alt="Trit_cp_278_BMGE_trace" src="https://user-images.githubusercontent.com/11645116/151118541-25faac2c-84f3-4609-8b17-0e8b178a9026.PNG">

**Comment by Proschnipser** [comment]
Were you able to solve the problem?
