### ISSUE TITLE
BEAST 1.10.4 shows BEAGLE library installed but no resources available

### ISSUE THREAD

**Issue by comradesoup** [beagle-dev/beagle-lib#177]
I have installed BEAGLE v3.1.0 and am trying to run BEAST. 
BEAGLE seems to have been installed correctly: 
```
(base) campbellmcgarvey@Campbells-MacBook-Air build % make test
Running tests...
Test project /Users/campbellmcgarvey/beagle-lib/build
    Start 1: hmctest
1/1 Test #1: hmctest ..........................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.07 sec
```
BEAST seems to recognize that BEAGLE is installed, but does not show that any of the resources are available: 
```

        BEAST v1.10.4 Prerelease #bc6cbd9, 2002-2018
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
                              
               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz
                              
             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk
                              
              David Geffen School of Medicine
           University of California, Los Angeles
                     msuchard@ucla.edu
                              
                Downloads, Help & Resources:
                  	http://beast.community
                              
Source code distributed under the GNU Lesser General Public License:
          	http://github.com/beast-dev/beast-mcmc
                              
                     BEAST developers:
	Alex Alekseyenko, Guy Baele, Trevor Bedford, Filip Bielejec, Erik Bloomquist, Matthew Hall,
	Joseph Heled, Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li,
	Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel,
          	Oliver Pybus, Chieh-Hsi Wu, Walter Xie
                              
                         Thanks to:
    	Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Using BEAGLE library v3.1.0 for accelerated, parallel likelihood evaluation
2009-, BEAGLE Working Group - https://beagle-dev.github.io/
Citation: Ayres et al (2012) Systematic Biology 61: 170-173 | doi:10.1093/sysbio/syr100


BEAGLE resources available:
```

I'm not sure if this is a BEAGLE issue or a BEAST issue, I am open to advice.

**Comment by giulioisac** [comment]
I have the same problem.

**Comment by trvrb** [comment]
I've just run into the same issue as well. In my case, I installed BEAGLE on M1 Mac via
```
brew install beagle
```

**Comment by ekamau** [comment]
Was this resolved? I am having trouble with this issue as well. What was the solution?

**Comment by xji3** [comment]
@ekamau If you installed beagle correctly, the issue might be that you didn't tell BEAST where to find beagle.  You might want to refer to issue #181 for a possible solution.
P.S. You might want to consider "re-install" beagle with the updated installer as well (just to be sure the installation is complete and correct).

**Comment by bpetros95** [comment]
still getting this issue.

`ls /usr/local/lib/*beagle* ` displays my beagle library in the proper location. anyone determine how to set BEAST to look in this location for the beagle library?

**Comment by ekamau** [comment]
Installing beagle on an M2 Mac and funny that I have run into this problem again. Anyone find a fix?

**Comment by xji3** [comment]
@ekamau I thought I gave you the solution.  See if you could find beagle binaries by `ls /usr/local/lib/*beagle*`.  If you see beagle binaries there, the problem is that you need to tell beast where to look for them (e.g., if you are running beast from command line).  In this case, you might want to add `-Djava.library.path=/usr/local/lib` to your beast command.  If you do not see beagle binaries from the `ls` command, the problem is that your beagle libraries did not compile.  Then you should post the exact compilation errors here.
