### ISSUE TITLE
"BEAGLE v4.0.0 for macOS universal" link is broken on github page

### ISSUE THREAD

**Issue by davidcannatella** [beagle-dev/beagle-lib#178]
Clicking this links gives me a 404 error.

**Comment by Tessa-Smith** [comment]
also for the [BEAGLE v4.0.0 for Windows 64-bit]

**Comment by trvrb** [comment]
Bumping this, just ran into this issue as well.

**Comment by Tessa-Smith** [comment]
Thanks Trevor
