### ISSUE TITLE
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path M1 MacOs BEAGLE v4

### ISSUE THREAD

**Issue by bastiaanvdroest** [beagle-dev/beagle-lib#181]
Hi,
I'm trying to run BEAST, but get stuck in the installation of BEAGLE. After installation of BEAGLE v3, I've now installed BEAGLE v4 which has support on the M1 chip of my Mac. However, I get the following output:

Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

Can you tell me what is happening and how to fix this?

Kind regards,
Bastiaan

**Comment by xji3** [comment]
Hi,
I just installed beagle using the v4 installer, it installed `/usr/local/lib/libhmsbeagle-jni.jnilib` for me.  You could check if beagle is correctly installed by `ls /usr/local/lib/*beagle*` and see if you find beagle library files.
It could be that BEAST doesn't know where to look for beagle.  It depends on how you run BEAST, it usually assumes the default location and calls beagle correctly (in this case `/usr/local/lib`).  If you are running BEAST from command line, you could tell BEAST your BEAGLE location by `java -jar -Djava.library.path=/usr/local/lib beast.jar` followed by your usual beast commands.
I hope this helps.
Best,
Xiang

**Comment by bastiaanvdroest** [comment]
Hi ,
Thanks for the response. I think that the default location of BEAST where to look for BEAGLE is not set to /usr/local/lib. When I use the command line and tell where to find BEAGLE it works for me. 
Is there a way to change the default location of BEAST to look for BEAGLE?
Best,
Bastiaan

**Comment by xji3** [comment]
Hi Bastiaan,
I honestly don't know the answer.  The reason is that I think it's preset already.  If you look at the `BEAST_location/bin/beast` script, you could see the last line being `java -Xms64m -Xmx2048m -Djava.library.path="$BEAST_LIB:/usr/local/lib:$LD_LIBRARY_PATH" -cp "$BEAST_LIB/beast.jar" dr.app.beast.BeastMain $*` which correctly sets the environment already.  And double-clicking on `bin/beast` just runs BEAST correctly for me.
I am closing this issue since BEAGLE is running correctly.  Please feel free to let us know if you need further help.
Best,
Xiang
