### ISSUE TITLE
Is libhmsbeagle no longer versioned?

### ISSUE THREAD

**Issue by thanasibakis** [beagle-dev/beagle-lib#182]
Hi!

I'm trying to have beagle 4.0.0 added to homebrew (version 3.1.2 is [already there](https://formulae.brew.sh/formula/beagle#default)), but the homebrew admins noticed that a change in the versioning for `libhmsbeagle` broke the `mrbayes` package on homebrew.

Quoting from Homebrew/homebrew-core#106781:

> Looks like libhmsbeagle is no longer versioned. Previously it was libhmsbeagle.1.dylib. Now, it is libhmsbeagle.dylib, and that's broken mrbayes. Would you know if this is intentional?
>
>This issue is actually pretty typical of a build system change, so I suspect that it is not.

The admins would like to check if this was intentional. Could you please help us out?

Thanks in advance!

**Comment by msuchard** [comment]
This was *not* intentional, and a patch to our new `cmake` build files would be much appreciated.

**Comment by thanasibakis** [comment]
Thanks for the quick reply! I just made a pull request. Admittedly I'm pretty new to working with cmake, so hopefully this patch helps, but please let me know if something could be corrected.

**Comment by thanasibakis** [comment]
Hi, just wanted to check in and see if the patch looks okay!

**Comment by chenrui333** [comment]
ping @msuchard, 🙏

**Comment by msuchard** [comment]
i think you solved it!

**Comment by thanasibakis** [comment]
Glad to hear! A quick favor to ask as a follow-up: would you be willing to publish a new "release" on the repo with this commit, so I can have beagle 4 added to homebrew? (No need to have a .pkg or .msi built, the source code archive should be sufficient for this purpose.)
