### ISSUE TITLE
JNI missing AWT compilation error

### ISSUE THREAD

**Issue by jhcuarta** [beagle-dev/beagle-lib#188]
Hi
While trying to install beagle-lib on ubuntu 22.04 using the command line "cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME ..", throws the following error

-- Could NOT find JNI (missing: AWT) 
CMake Error at CMakeLists.txt:72 (message):
  No JNI includes and libraries found

**Comment by xji3** [comment]
@jhcuarta Did you install jdk?  As in the command `sudo apt-get install cmake build-essential autoconf automake libtool git pkg-config openjdk-11-jdk`, the last one is the jdk package.  The error indicates missing JDK to build JNI (to interface with java as used by BEAST for example).  If you are using BEAGLE with BEAST, then you probably don't have to build the JNI, you can do this by adding `-DBUILD_JNI=OFF` in the cmake command.

**Comment by jhcuarta** [comment]
Hi
Indeed openjdk-11-jdk was missing, I had installed java 18. Thanks a lot

Best regards
