### ISSUE TITLE
Error File INSTALL

### ISSUE THREAD

**Issue by wbender1** [beagle-dev/beagle-lib#190]
Hello,
As part of the installation of BEAGLE it is trying to copy an executable file into my usr folder, which does not executable privileges. I am running on an M1 Pro chip and have previously fixed the java jdk issue.
CMake Error at libhmsbeagle/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/Users/wbender/beagle-lib/build/libhmsbeagle/libhmsbeagle.1.dylib" to
  "/usr/local/lib/libhmsbeagle.1.dylib": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)

Any help greatly appreciated.

**Comment by xji3** [comment]
Please try `sudo make install`.
