### ISSUE TITLE
BEAGLE doesn't see GPU in BEAST2

### ISSUE THREAD

**Issue by trilisser** [beagle-dev/beagle-lib#191]
Hi there! I installed the last BEAGLE version (4.0.0) for BEAST2 and it doesn't see GPU (CPU only).
>--- BEAGLE RESOURCES ---
>
>0 : CPU (x86_64)
>   Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX >SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_SSE VECTOR_NONE >THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU

I don't know how to specify a path to the CUDA library for BEAGLE. 

-Operation system: Ubuntu 22.04
-GPU: GTX3070

**Comment by xji3** [comment]
@trilisser Thanks for the report.  Did you install `cuda-toolkit`?  Cmake should be able to find cuda automatically if you followed our recommendation of getting cuda through http://www.nvidia.com/object/cuda_get.html.  Please let me know if the problem persists.

**Comment by trilisser** [comment]
@xji3 It was my mistake with `cmake`. I did `cmake -DBUILD_OPENCL=OFF ..` but after `make install`, as it described in the Instructions :) It should be done before `make install`.
