### ISSUE TITLE
error when running "cmake -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF .."

### ISSUE THREAD

**Issue by liamxg** [beagle-dev/beagle-lib#202]
(base) simon@simon-puro build % cmake -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF ..
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT) 
CMake Error at CMakeLists.txt:98 (message):
  No JNI includes and libraries found

-- Configuring incomplete, errors occurred!
See also "/Users/simon/Desktop/0/1/group/beagle-lib/build/CMakeFiles/CMakeOutput.log".
See also "/Users/simon/Desktop/0/1/group/beagle-lib/build/CMakeFiles/CMakeError.log".

**Comment by msuchard** [comment]
either install JNI and ensure `JAVA_HOME` is correctly set, or do not build with JNI via `-DBUILD_JNI=OFF`
