### ISSUE TITLE
faile to make test for linux-aarch64

### ISSUE THREAD

**Issue by yejianbang** [beagle-dev/beagle-lib#208]
Dear author, hello！

I'm installing beagle-lib on an aarch64 architecture server. The installation succeeds, but it fails during testing.
I compared an x86 architecture environment. If **cmake .. -DBUILD_SSE=OFF**, the test also fails on x86. Otherwise, the test succeeds.So I'm guessing it's the sse instruction set.

But the server I'm on now is an arch64 architecture.You updated sse2neon.h on version 4.0.1 so that it compiles successfully.But in fact, the test will still fail.

[root@localhost build]# make test
Running tests...
Test project /path/to/beagle-lib/beagle-lib-4.0.1/build
    Start 1: hmctest
1/1 Test #1: hmctest ..........................***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - hmctest (Failed)
Errors while running CTest
make: *** [Makefile:120: test] Error 8

[root@localhost build]# cat Testing/Temporary/LastTest.log
Start testing: Oct 26 16:10 CST
----------------------------------------------------------
1/1 Testing: hmctest
1/1 Test: hmctest
Command: "/path/to/beagle-lib/beagle-lib-4.0.1/build/examples/hmctest"
Directory: /path/to/beagle-lib/beagle-lib-4.0.1/build/examples
"hmctest" start time: Oct 26 16:10 CST
Output:
----------------------------------------------------------
Failed to obtain BEAGLE instance

Available resources:
        Resource 0:
                Name : CPU (arm64)
                Desc :
                Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG VECTOR_NONE THREADING_NONE FRAMEWORK_CPU

<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"hmctest" end time: Oct 26 16:10 CST
"hmctest" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Oct 26 16:10 CST

Is there a solution for the aarch64 architecture?

We look forward to your reply, thank you again！

**Comment by yejianbang** [comment]
In addition, I tried to instrument the trace code found：
①“instance ” in X86 is “0”
②“instance” in aarch64 is “-6”

so，Caused it to get into this branch

    if (instance < 0) {
            fprintf(stderr, "Failed to obtain BEAGLE instance\n\n");
            exit(1);
    }


How is the value of “instance” determined?

**Comment by msuchard** [comment]
there are no official tests.   i will disable `make test` as this seems to cause confusion.

**Comment by yejianbang** [comment]
@msuchard 
Thank you for your reply！
I hope you can do official testing under aarch64, and I can assist you until a full aarch64 version is released.
I wish you a happy life and a happy family.
