### ISSUE TITLE
Installed Beauti but BEAST does not recognize

### ISSUE THREAD

**Issue by StephanieRodrigues** [beagle-dev/beagle-lib#210]
Hi Everyone, 
I am pretty new to BEAST/BEAUTI world.
I am trying to use BEAST. I followed all the installation protocols, and installed JAVA and Beauti but when I opened BEAST and marked the box "Show list of BEAGLE available resources and quit", nothing showed up on my prompt (image 1). 
I made sure my beauti typing > ls usr/local/lib/*beagle* and the library is over there I guess (image 2). 

I do not know how to proceed.
I have a MacBook Apple M2 CHIP / OS system 14.1.1
Thanks!

![image1](https://github.com/beagle-dev/beagle-lib/assets/47237439/c8c1816a-cd33-4f80-b939-2f97df416a08)
![image2](https://github.com/beagle-dev/beagle-lib/assets/47237439/56cd7a57-0008-48a1-97f7-244dbecff21a)

**Comment by xji3** [comment]
Hi @StephanieRodrigues, Welcome to the BEAGLE/BEAST community.  How did you run BEAST?  You might want to include the path to your path to BEAGLE for BEAST.  Maybe a command that starts with `java -Djava.library.path=/path_to_beagle -jar /path_to_beast/beast.jar` and followed by the regular BEAST command options (please remember to replace `path_to_beagle` with the actual path to the directory that contains the beagle `.so` files).

**Comment by StephanieRodrigues** [comment]
Hi, 
Thanks for the fast answer! I am running using the graphical interface not on the command line. I decided to download the Oracle Java 8 because Java 6 is for the older versions of OS. Now the error I am getting when I request to see the list of available BEAGLE resources is this: 
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path

**Comment by xji3** [comment]
Hi @StephanieRodrigues,  
Hmm.  I could replicate your error.  I think that it's because the default path to beagle installation was only included in the beast script but not the app.  If you call the GUI from command line by `/Applications/BEAST\ v1.10.4/bin/beast`, it should be able to find BEAGLE (if they were installed under `/usr/local/lib`).

**Comment by StephanieRodrigues** [comment]
Hi I tried to do what you did and now I got this: 
/Applications/BEAST v1.10.4/bin/beast: Not a directory

**Comment by xji3** [comment]
@StephanieRodrigues 
My bad.  You need to modify the path to what you have.  If you drag the `BEAST` folder into the terminal, it converts to the path, and then you add `/bin/beast` to it (without any space) and press enter.  Please let me know if that works.

**Comment by StephanieRodrigues** [comment]
I drag it, then showed up this: /Applications/BEAST\ v1.10.4/    I added the bin/beast right after without any space and got same error!

**Comment by xji3** [comment]
Could you please verify where you installed the beagle library?  You can drag it into terminal to find out the path.

Xiang Ji
________________________________

**Comment by StephanieRodrigues** [comment]
andamlabmbp6:~ mm635664$ ls /usr/local/lib/*beagle*
/usr/local/lib/libhmsbeagle-cpu-sse.21.so
/usr/local/lib/libhmsbeagle-cpu-sse.31.so
/usr/local/lib/libhmsbeagle-cpu-sse.40.so
/usr/local/lib/libhmsbeagle-cpu-sse.so
/usr/local/lib/libhmsbeagle-cpu.21.so
/usr/local/lib/libhmsbeagle-cpu.31.so
/usr/local/lib/libhmsbeagle-cpu.40.so
/usr/local/lib/libhmsbeagle-cpu.so
/usr/local/lib/libhmsbeagle-cuda.21.so
/usr/local/lib/libhmsbeagle-cuda.31.so
/usr/local/lib/libhmsbeagle-jni.jnilib
/usr/local/lib/libhmsbeagle-opencl.21.so
/usr/local/lib/libhmsbeagle-opencl.40.so
/usr/local/lib/libhmsbeagle-opencl.so
/usr/local/lib/libhmsbeagle.1.dylib
/usr/local/lib/libhmsbeagle.dylib

**Comment by xji3** [comment]
Hi @StephanieRodrigues,
Sorry for the delay in response.  I got an official solution/patch for this:

> Aug 25, 2022, 1:44:19 AM
> to beast-users
> To the best of my understanding, these are not issues with BEAGLE.   BEAGLE v4 on Mac is now a universal build that supports x86 and ARM64 execution automatically.  Rather, the issues seem to be related to Apple changing the default search paths on M1 systems when executing BEAST through the GUI application.    I have found a patch that works and expect to provide an updated BEAST release relatively soon.   In the meantime, here's how one can make the patch on their local computer:
> 
> 1. Open in Finder the directory that contains the BEAST v1.10.4.app
> 2. Control-click to Show Package Contents
> 3. Open in a text editor Info.plist
> 4. Change this line:
>        <string>-Xmx2048M</string>
>    to now read
>         <string>-Xmx2048M -Djava.library.path=/usr/local/lib</string>
> 5. Save and re-execute BEAST v1.10.4.app
> 
> As far as I can tell, these issues do not arise when using the command-line script `beast` since that script already adds the necessary java.library.path VM option.
> 
> best, Marc

**Comment by StephanieRodrigues** [comment]
Thank you Xiang Ji and Marc, this finally worked for me.
