### ISSUE TITLE
hmctest: symbol lookup error

### ISSUE THREAD

**Issue by ypchan** [beagle-dev/beagle-lib#211]
Dear authors,

I installed in specified directory, then I try to test it `cd build && make test`. An error happened:
`hmctest: symbol lookup error: /home/ychen/software/beagle-lib/build/examples/hmctest: undefined symbol: beagleCalculateCrossProductDerivative`

Thanks

**Comment by bredelings** [comment]
Do you have another version of BEAGLE installed on your system?

If you are running on Linux, what does `ldd examples/hmctest` show?
