### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by pikkazz** [beagle-dev/beagle-lib#218]
My NVIDIA and CUDA info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:41:00.0 Off |                    0 |
| N/A   23C    P0    25W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:45:00.0 Off |                    0 |
| N/A   23C    P0    25W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Using BEAGLE DataLikelihood Delegate
CUDA error: "Unknown error" (222) from file </home/lylyang/beagle-lib/libhmsbeagle/GPU/GPUInterfaceCUDA.cpp>, line 284.

I've switched to a different server for deployment, but I always get this problem.

**Comment by xji3** [comment]
@pikkazz Could you provide more information about how you installed BEAGLE?  It seems that BEAGLE failed to initiate its cuda kernels.
