### ISSUE TITLE
Error running MrBayes with CUDA

### ISSUE THREAD

**Issue by obbrz** [beagle-dev/beagle-lib#221]
I'm getting this error when I try using GPU in MrBayes. Beagle was compiled with CUDA and installed into /usr/local. I disabled OpenCL and JNI when compiling and there were no errors.

`Running benchmarks to automatically select fastest BEAGLE resource... CUDA error: "Unknown error" (218) from file </home/burak/beagle-lib/libhmsbeagle/GPU/GPUInterfaceCUDA.cpp>, line 284.`

**Comment by NilaBlueshirt** [comment]
I recently had a similar error when using beagle with beast1, and I re-installed beagle from the source codes, which resolved the error. My faulty beagle install was by spack on a linux cluster. Hope this info helps!
