### ISSUE TITLE
 install beagle error

### ISSUE THREAD

**Issue by pathogen-detection** [beagle-dev/beagle-lib#223]
I tried to install the library with cuda driver 12.5 (on an Ubuntu 20.04 machine). However, when compiling I met the following error:
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
make[2]: *** [libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/build.make:146: libhmsbeagle/GPU/CMake_CUDA/libhmsbeagle-cuda.so.40.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:281: libhmsbeagle/GPU/CMake_CUDA/CMakeFiles/hmsbeagle-cuda.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Some clue? Or have I installed error versions of cuda

Cheers

**Comment by xji3** [comment]
@pathogen-detection You need to install both the driver and cuda toolkit ([https://developer.nvidia.com/cuda-downloads](https://developer.nvidia.com/cuda-downloads)).  Please follow the installation carefully.  The default installation location of cuda toolkit on Ubuntu is `/usr/local/cuda`.  You could check if it exists.  You could also check by running command `nvidia-smi` to see your GPU usage which also displays your driver and cuda versions.
