### ISSUE TITLE
The GPU could not be found in the HPC

### ISSUE THREAD

**Issue by pikkazz** [beagle-dev/beagle-lib#224]
After installing with conda on the Beast official website, only CPU 0 is displayed after entering Beast -beagle_info.It's not the first time I've used it, everything works fine on a PC, but it's frustrating that there are always problems when deploying HPC.

**Comment by xji3** [comment]
@pikkazz Could you please re-install BEAGLE following our guide [(https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions)](https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions)?  I don't think the conda one is official.  Please let me know if you encounter any difficulties.

**Comment by xji3** [comment]
close for now
