### ISSUE TITLE
beagle compilation fails on a new machine

### ISSUE THREAD

**Issue by jheled** [beagle-dev/beagle-lib#83]
On this command, with a cryptic error message. The 

/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -march=native -O3 -module -avoid-version   -o libhmsbeagle-jni.la -rpath /usr/local/lib libhmsbeagle_jni_la-beagle_BeagleJNIWrapper.lo -L../../libhmsbeagle -lhmsbeagle -ldl
libtool: link: unsupported hardcode properties
libtool: link: See the libtool documentation for more information.
libtool: link: Fatal configuration error.

Linux weakest 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

weakest:~/tmp > cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

**Comment by msuchard** [comment]
Unable to reproduce.
