### ISSUE TITLE
Different results when using double precision beagle

### ISSUE THREAD

**Issue by josephwb** [beagle-dev/beagle-lib#84]
Not positive if this is a beagle issue, or a MrBayes-beagle-integration issue.

We've been running MrBayes (v3.2.5) with and without beagle on very simple simulated alignments (JC69 model). We've noticed that results differ greatly depending on whether/how we use beagle.

For instance, here is the LnL trace without and with beagle (beagleprecision=double, the default it seems):
![lnlik](https://cloud.githubusercontent.com/assets/808499/9089081/79b03df6-3b61-11e5-8d20-24e225e3f48b.png)
Using beagle with ```beaglescaling=dynamic``` gives ludicrously higher likelihoods, but ```beaglescaling=always``` are quite different too. Using ```beagleprecision=single``` gives results identical to results without using beagle.

The real concern, however, is that we've also noticed that both node support and parameter estimates can vary considerably.

For instance, here is a trace of the stationary frequency of T (recall that this was simulated under JC69):
![pi t](https://cloud.githubusercontent.com/assets/808499/9089365/ce6bcb7a-3b62-11e5-8280-269dfa2207f2.png)
Again, using ```beagleprecision=single``` gives results identical to results without using beagle.

Here is the information about our installed version of beagle (we have been using the cpu):
```
MrBayes > showbeagle

   Available resources reported by beagle library:
	Resource 0:
	Name: CPU
	Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE VECTOR_SSE THREADING_NONE THREADING_OPENMP

	Resource 1:
	Name: Quadro 2000
	Desc: Global memory (MB): 1023 | Clock speed (Ghz): 1.25 | Number of cores: 192
	Flags: PROCESSOR_GPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE THREADING_NONE

   BEAGLE vesion: 2.1.2
```
The alignment file used above can be found [here](https://www.dropbox.com/s/aq1uxgo0ds83hbp/tree1.nex?dl=0).

So, should double-precision beagle not be used? Or is my compilation faulty?

Thanks.
JWB.

**Comment by msuchard** [comment]
Likely due to a bug in `MrBayes`.  Any further information?

**Comment by josephwb** [comment]
I haven't tried with the new version of MrBayes; I believe v3.2.5 did indeed have bugs. Will try the new version within a few days (and replace the input file I link to above but have since deleted).

**Comment by josephwb** [comment]
I re-ran things with MrBayes v3.2.6 (and original beagle install) and the artefact indeed goes away.
