### ISSUE TITLE
BEAGLE fails to compile for Ubuntu 16.04 OpenCL

### ISSUE THREAD

**Issue by maxbiostat** [beagle-dev/beagle-lib#91]
When I $make check

``` bash
Making check in libhmsbeagle
make[1]: Entering directory '/home/max/beagle-lib/libhmsbeagle'
Making check in GPU
make[2]: Entering directory '/home/max/beagle-lib/libhmsbeagle/GPU'
Making check in kernels
make[3]: Entering directory '/home/max/beagle-lib/libhmsbeagle/GPU/kernels'
make  check-am
make[4]: Entering directory '/home/max/beagle-lib/libhmsbeagle/GPU/kernels'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/GPU/kernels'
make[3]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/GPU/kernels'
make[3]: Entering directory '/home/max/beagle-lib/libhmsbeagle/GPU'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/GPU'
make[2]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/GPU'
Making check in CPU
make[2]: Entering directory '/home/max/beagle-lib/libhmsbeagle/CPU'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/CPU'
Making check in plugin
make[2]: Entering directory '/home/max/beagle-lib/libhmsbeagle/plugin'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/plugin'
make[2]: Entering directory '/home/max/beagle-lib/libhmsbeagle'
make[2]: Leaving directory '/home/max/beagle-lib/libhmsbeagle'
make[1]: Leaving directory '/home/max/beagle-lib/libhmsbeagle'
Making check in libhmsbeagle/JNI
make[1]: Entering directory '/home/max/beagle-lib/libhmsbeagle/JNI'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/max/beagle-lib/libhmsbeagle/JNI'
Making check in examples
make[1]: Entering directory '/home/max/beagle-lib/examples'
Making check in genomictest
make[2]: Entering directory '/home/max/beagle-lib/examples/genomictest'
make  genomictest genomictest.sh
make[3]: Entering directory '/home/max/beagle-lib/examples/genomictest'
make[3]: 'genomictest' is up to date.
make[3]: 'genomictest.sh' is up to date.
make[3]: Leaving directory '/home/max/beagle-lib/examples/genomictest'
make  check-TESTS
make[3]: Entering directory '/home/max/beagle-lib/examples/genomictest'
make[4]: Entering directory '/home/max/beagle-lib/examples/genomictest'
FAIL: genomictest.sh
============================================================================
Testsuite summary for libhmsbeagle 2.1.2
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See examples/genomictest/test-suite.log
Please report to beagle-dev@googlegroups.com
============================================================================
Makefile:711: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/max/beagle-lib/examples/genomictest'
Makefile:817: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/max/beagle-lib/examples/genomictest'
Makefile:890: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/max/beagle-lib/examples/genomictest'
Makefile:409: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/max/beagle-lib/examples'
Makefile:607: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

and when $java -Djava.library.path=/home/max/lib -jar beast.jar -beagle_info:

``` bash

                  BEAST v1.8.4, 2002-2016
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
...

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.
```

May or may not be connected to #89.

Happy to provide more details on the system.

**Comment by msuchard** [comment]
Two things:
1. Can you post `examples/genomictest/test-suite.log`?
2. Do other (non-BEAST) OpenCL programs work on your system?

**Comment by maxbiostat** [comment]
I'm currently investigating (2), because I tried a previous version of beagle and it didn't work either, what made me suspect of problems with my OpenCL.

Regarding (1):
```bash
=============================================================
   libhmsbeagle 2.1.2: examples/genomictest/test-suite.log
=============================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: genomictest.sh
====================


OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

Simulating genomic DNA with 16 taxa and 10000 site patterns (5 reps)


OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

Simulating genomic 64-state data with 10 taxa and 100 site patterns (5 reps)

FAIL genomictest.sh (exit status: 255)

```

**Comment by maxbiostat** [comment]
can't get OpenCL to work on my system, so closing this for the time being.

**Comment by GuyBaele** [comment]
Just had this exact same problem on one of our servers, with the exact same content in examples/genomictest/test-suite.log.
Strange thing though: we have 2 different types of servers, both recently reinstalled by our IT department. On the older ones: no problems installing BEAGLE, but the more recent ones seem fine.

Trying the following, suggested by Andrew on the user list, did not help:
./configure --prefix=$HOME --without-opencl

and the error prevails:
BEAST v1.9.0pre20170207 Prerelease #20fe946, 2002-2017
...
OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

**Comment by maxbiostat** [comment]
what's the output of 
```bash
$ clinfo
```
?

**Comment by GuyBaele** [comment]
The program 'clinfo' is currently not installed. To run 'clinfo' please ask your administrator to install the package 'clinfo'

Not sure how this matters though ...

**Comment by maxbiostat** [comment]
it matters because of @msuchard's point 2, above. I was eventually able to fix my system's OpenCL and get BEAGLE to work fine. The problem was indeed with the OpenCL installation.

**Comment by GuyBaele** [comment]
I have a system where clinfo says: The program 'clinfo' is currently not installed. To run 'clinfo' please ask your administrator to install the package 'clinfo'

And yet BEAST+BEAGLE works fine on it ...

Was it sufficient to install ocl-icd-opencl-dev ?

**Comment by msuchard** [comment]
Can you run in `gdb` and get more debug info?

**Comment by GuyBaele** [comment]
Will do, as soon as I get install privileges ...

**Comment by msuchard** [comment]
Can you create a `docker` container that reproduces this issue?

**Comment by maxbiostat** [comment]
clinfo is not **required**, it's just a convenient wrapper. But it'd help diagnose whether the OpenCL installation is faulty.

**Comment by GuyBaele** [comment]
@msuchard No, but I can get you a docker container that works fine on that very same system ...

**Comment by GuyBaele** [comment]
So when I perform a clean install of BEAGLE on my docker instance, I get the warnings:

configure: WARNING: OpenCL not found or disabled.  OpenCL implementation  will not be built. If OpenCL support is desired, check the path to OpenCL and specify --with-opencl=/path/to/opencl

configure: WARNING: NVIDIA CUDA nvcc compiler not found or CUDA support disabled.  CUDA implementation will not be built. If CUDA support is desired, check the path to CUDA and specify --with-cuda=/path/to/cuda

That's all fine, and the make checks all pass without problems.
But it seems like the --without-opencl flag for configure isn't really making much of a difference on my actual system. I do get the same warnings, but make check fails, and I still get the same error message related to OpenCL (when running genomictest for example):
OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

Any other way I can try to switch off the use of OpenCL?

**Comment by GuyBaele** [comment]
@maxbiostat output of clinfo:
Number of platforms                               0

**Comment by GuyBaele** [comment]
After installing beignet, I get:
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

OpenCL error: CL_DEVICE_NOT_FOUND from file <GPUInterfaceOpenCL.cpp>, line 118.

**Comment by GuyBaele** [comment]
sudo apt-get remove ocl-icd-libopencl1
and rebuilding BEAGLE fixes this issue.

**Comment by rafaeltiveron** [comment]
Same problem here in Linux Mint 20.04 Ulyana 64 bits
But I cannot remove "ocl-icd-libopencl1" because of "nvidia-opencl-dev" is installed and will make a mess on my system..
"--without-opencl" is not solving the problem
Anyother way?

**Comment by rafaeltiveron** [comment]
Whatever..
`apt-get install libhmsbeagle-java libhmsbeagle-dev mrbayes`
Let's see if this works..

**Comment by cement-head** [comment]
Did that solve your problem?
