### ISSUE TITLE
Where does the binary package for Mac OS X download beagle? 

### ISSUE THREAD

**Issue by evanbiederstedt** [beagle-dev/beagle-lib#93]
After downloading and installing the binary package `BEAGLE-2.1.2.pkg` for Mac OS X, I tried downloading MrBayes

I get the following error at `./configure`:
```

checking for /usr/local/include/libhmsbeagle/libhmsbeagle/beagle.h... no
checking for /usr/local/include/libhmsbeagle-1/libhmsbeagle/beagle.h... no
configure: error: beagle's library include file beagle.h is not found neither in
         /usr/local/include/libhmsbeagle/libhmsbeagle/ nor in
         /usr/local/include/libhmsbeagle-1/libhmsbeagle/. You should either install
         beagle library from http://code.google.com/p/beagle-lib/ or disable use of
         beagle library by invoking configure script with option --with-beagle=no.
         Note: without beagle library MrBayes may run slower.
```

Naturally, I could change the path in the configuration file to avoid this error, but I'm not sure where "BEAGLE-2.1.2.pkg" installs Beagle. Where is this? Can users manually set the path? 

Thanks!

**Comment by msuchard** [comment]
Headers get installed into `/usr/local/include/libhmsbeagle-2`.  The `MrBayes` source code is still looking for `beagle` version 1.  Versions are backwards compatible, so you can add a symbolic link from `libhmsbeagle-2` to `libhmsbeagle`.

If you want to manually set your install path, please download the `beagle` source code and compile by hand with `./configure --prefix=<what you want>`.
