### ISSUE TITLE
beagle_info problem

### ISSUE THREAD

**Issue by wpwupingwp** [beagle-dev/beagle-lib#98]
I built beagle-lib with cuda-toolkit-8.0 in Debian Stretch.
Now I run 
`beast2-mcmc -beagle_info`
it shows
```
BEAGLE resources available:
0 : CPU
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_SSE VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_CPU


1 :        Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (OpenCL 1.2 (Build 25))
    Global memory (MB): 56325
    Clock speed (Ghz): 2.60
    Number of multiprocessors: 16
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_NONE THREADING_NONE PROCESSOR_CPU FRAMEWORK_OPENCL


2 : GeForce GTX 1070 (OpenCL 1.2 CUDA)
    Global memory (MB): 8107
    Clock speed (Ghz): 1.77
    Number of multiprocessors: 15
    Flags: PRECISION_SINGLE PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO SCALING_ALWAYS SCALERS_RAW SCALERS_LOG VECTOR_NONE THREADING_NONE PROCESSOR_GPU FRAMEWORK_OPENCL
```
It said that GPU only has 15 cores, but GTX 1070 has 1920 cores.
I noticed it because I found that "-beagle_GPU" is not as fast as I thought.
Please help me.

Ping Wu

**Comment by GuyBaele** [comment]
There is indeed a reporting problem when it comes to the number of cores and such for these latest GPU cards. However this does not affect performance. The GTX 1070 has limited FP64 capabilities compared to scientific computing cards of the Tesla series though. So running a GTX 1070 in single precision should be really fast, in double precision not so much.

**Comment by wpwupingwp** [comment]
Thank you very much. :+1:
