### ISSUE TITLE
Make check FAILS genomictest.sh

### ISSUE THREAD

**Issue by Pejvak1** [beagle-dev/beagle-lib#99]
Hi all,

I am in an urgent need for help, as I need to get the parallel version of mrBayes to work before my Master's project ends; I would immensely appreciate a quick response.

I have tried everything, and fixed some issues along the way, but no matter what, the make check fails the genomictest.sh example. I get the following output:

make  check-TESTS
make[3]: Entering directory '/home/pejvak/beagle-lib/examples/genomictest'
make[4]: Entering directory '/home/pejvak/beagle-lib/examples/genomictest'
FAIL: genomictest.sh
============================================================================
Testsuite summary for libhmsbeagle 2.1.2
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See examples/genomictest/test-suite.log
Please report to beagle-dev@googlegroups.com
============================================================================
Makefile:711: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/pejvak/beagle-lib/examples/genomictest'
Makefile:817: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/pejvak/beagle-lib/examples/genomictest'
Makefile:890: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/pejvak/beagle-lib/examples/genomictest'
Makefile:409: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/pejvak/beagle-lib/examples'
Makefile:607: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

and the following is the report log of the test-suite.log file of the genomictest:

=============================================================
   libhmsbeagle 2.1.2: examples/genomictest/test-suite.log
=============================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: genomictest.sh
====================

./genomictest.sh: line 1: 18642 Segmentation fault      (core dumped) ./genomictest
./genomictest.sh: line 2: 18657 Segmentation fault      (core dumped) ./genomictest --states 64 --sites 100 --taxa 10
FAIL genomictest.sh (exit status: 139)

Cheers,
Pejvak.

**Comment by ayresdl** [comment]
Hi Pejvak, it sounds like an issue specific to codon models and one of the OpenCL resources BEAGLE can use.  You can probably skip the 'make check' step and run your MrBayes analyses without issue.

**Comment by Pejvak1** [comment]
Hi Daniel,

Thank you very much for the prompt reply. That's great to know, though I'd get on with it as soon as I resolve another issue haha. This time with installing mrBayes itself. 

Cheers,
Pej.

**Comment by Pejvak1** [comment]
Hi again Daniel,

I just installed the mpi-enabled MrBayes, but it comes back with the following error:

                            MrBayes v3.2.6 x64

                      (Bayesian Analysis of Phylogeny)

                             (Parallel version)
                         (8 processors available)

              Distributed under the GNU General Public License


               Type "help" or "help <command>" for information
                     on the commands that are available.

                   Type "about" for authorship and general
                       information about the program.


MrBayes > Showbeagle

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

OpenCL error: Unknown error from file <GPUInterfaceOpenCL.cpp>, line 111.

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53643,1],0]
  Exit code:    255


I seems like it has something to do with the former issue?
any idea what the problem is?

Cheers,
Pej.

**Comment by Pejvak1** [comment]
Update: I properly installed the intel OpenCL, however, while Showbeagle command no longer returns any errors, it does not show my graphics card as a Beagle source.

I am confident Cuda is installed, as I received no errors, nor for Cuda neither for Opencl, when installing the Beagle itself. That is except for the genomictest.sh failure (as mentioned above) of course.

I am going to uninstall and reinstall Beagle with the --with cuda=usr/local/cuda specification and will then report the outcome.

Cheers,
Pej.

**Comment by Pejvak1** [comment]
I have finally got Beagle to work with my gpu. Beagle passes all the tests and MrBayes runs on the gpu too. However, there seems to be a problem with the speed, which will be addressed in a follow up post. I will now close this, but the following is a highlight of the major issues (I have omitted many specific minor issues I had during installation of various things) addressed.

#Note1 | The problem (discussed above) arose from the fact that Beagle made no complaints about the absence of a working Cuda platform. I assumed it would, if Cuda was not installed properly, as it did complain about missing OpenCL and Cuda, when I tested Beagle installation before installing either Cuda and OpenCl.

#Note2 | After discovering cuda was not installed properly, trying multiple different installation pathways failed me, until I noticed that every solution online consistently pointed to `nvidia-smi` command, which was just not being recognised as a command, no matter how many times I purged my system from nvidia drivers and installed the latest driver, or other drivers. This command shows you the cuda-enabled hardwars available on your system. If you have the right cuda-enabled gpu driver this command should work. This was, admittedly, partly due to my own negligence of the non-propitiatory drivers listed in my ubuntu-driver. By changing the driver to one of the open source ones, I could successfully install Cuda.

#Note3 | I had to use `sudo apt-get install nvidia-cuda-toolkit` in order for Beagle to pass all the tests.
